# Generated by Django 4.2.19 on 2025-03-08 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0002_customuser_address_customuser_polling_booth'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='age',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
