# Generated by Django 4.2.19 on 2025-03-08 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0003_customuser_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
