# Generated by Django 4.2.19 on 2025-03-08 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0004_customuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='Voted',
            field=models.CharField(default='Not Voted', max_length=10),
        ),
    ]
